### ISSUE TITLE
There's a problem with the dual-channel mode; the output folder doesn't contain pass2, and the result only includes pass1 and the merged result (pass1)

### ISSUE THREAD

**Issue by weifu8435** [meizhong986/WhisperJAV#72]
There's a problem with the dual-channel mode; this time, the output folder doesn't contain pass2, and the result only includes pass1 and the merged result (pass1).
Furthermore, the program logs did not show any logs for transcribing pass2 or merging subtitles.

<img width="891" height="288" alt="Image" src="https://

<img width="1195" height="910" alt="Image" src="https://github.com/user-attachments/assets/57518ae3-6c70-4c9b-ab78-f6d29b23e114" />

github.com/user-attachments/assets/33e71599-5785-4ebf-88bf-8860b4eaed11" />

**Comment by weifu8435** [comment]
<img width="742" height="229" alt="Image" src="https://github.com/user-attachments/assets/86fb2a84-48fe-44f4-b757-5dca04fbcd0e" />

**Comment by weifu8435** [comment]
This is the state after the video transcription is completed; there is no transcription pass2 log.

<img width="1268" height="326" alt="Image" src="https://github.com/user-attachments/assets/11fa148a-a166-4883-a140-b945e4a2eff8" />

**Comment by meizhong986** [comment]
Thanks for the detailed bug report. 
It seems that while fixing the earlier bug I have introduced a new bug. 
It will be fixed in the next release.

**Comment by meizhong986** [comment]
@weifu8435 , I just pushed version 1.7.1 out. 
That has fixed the bug.

**Comment by weifu8435** [comment]
> [@weifu8435](https://github.com/weifu8435) , I just pushed version 1.7.1 out. That has fixed the bug.

This problem persists and hasn't been improved; both of my vads are set to silre.

**Comment by weifu8435** [comment]
<img width="138" height="192" alt="Image" src="https://github.com/user-attachments/assets/a0e7098d-61b0-4901-be10-619f0485f255" />

**Comment by meizhong986** [comment]
I just tested it again and it works on my side.
I tested it exactly with the same settings as in your report.
See below screenshots.
 
Is the problem happening on any media --i.e. have you tried it any other video,  or is it on a specific video?   

--- 


<img width="1170" height="518" alt="Image" src="https://github.com/user-attachments/assets/d408f2bd-9404-445d-ac8f-34672599b70f" />
<img width="446" height="462" alt="Image" src="https://github.com/user-attachments/assets/1950d3eb-91c9-4812-b482-fd4f28788ac9" />

**Comment by weifu8435** [comment]
> I just tested it again and it works on my side. I tested it exactly with the same settings as in your report. See below screenshots.
> 
> Is the problem happening on any media --i.e. have you tried it any other video, or is it on a specific video?
> 
> <img alt="Image" width="1170" height="518" src="https://private-user-images.githubusercontent.com/148393222/522375998-d408f2bd-9404-445d-ac8f-34672599b70f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ5MjE4NTksIm5iZiI6MTc2NDkyMTU1OSwicGF0aCI6Ii8xNDgzOTMyMjIvNTIyMzc1OTk4LWQ0MDhmMmJkLTk0MDQtNDQ1ZC1hYzhmLTM0NjcyNTk5YjcwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwNVQwNzU5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTM3YmYxZTcwMGU0ZGRjNzY2YzgwZjgzNjA0MDk4NzA3NGI3N2ViMjFlOTdlMDA0ZGZjYTBjZTNmYzZkNTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kfuDXdgM6s7pBNYkdWbcewnQP0atpAUs36P3sDsr-Ag"> <img alt="Image" width="446" height="462" src="https://private-user-images.githubusercontent.com/148393222/522375999-1950d3eb-91c9-4812-b482-fd4f28788ac9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ5MjE4NTksIm5iZiI6MTc2NDkyMTU1OSwicGF0aCI6Ii8xNDgzOTMyMjIvNTIyMzc1OTk5LTE5NTBkM2ViLTkxYzktNDgxMi1iNDgyLWZkNGYyODc4OGFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwNVQwNzU5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGE0YjE5MTdiNjQzZDM3MTM1MTVkZTI0NzEyMzIyMGEyZjcwZjkyOThhMTcxODYyMjE1YWQxYmUwYWVmOWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Wf0QFPFid76qjSkJKLImrVwRe9b41_hmjzU-i4qIWp8">

Why is it that bug from the first time happening again, and the merged result is pass2?

<img width="114" height="94" alt="Image" src="https://github.com/user-attachments/assets/57759845-4cf1-4515-9053-a40b623ade50" />

<img width="1195" height="911" alt="Image" src="https://github.com/user-attachments/assets/12b408dd-5d75-448e-a7c1-b6fb627a765c" />

**Comment by weifu8435** [comment]
I tested several videos, and in one of them, pass1, the transcription wasn't complete; only 6 lines were transcribed before being merged. This mode has too many bugs.

<img width="1026" height="520" alt="Image" src="https://github.com/user-attachments/assets/697e3078-bdb7-4405-8fba-ecc6314af941" />
Have you noticed this bug? It happens when transcribing many videos, and occasionally one line is very long. Hopefully, this can be optimized.

**Comment by weifu8435** [comment]
This problem has occurred not just once, but many times; occasionally a particular line is exceptionally long, as if it were an interjection.

**Comment by weifu8435** [comment]
The error has occurred again.

<img width="1195" height="911" alt="Image" src="https://github.com/user-attachments/assets/1e707c77-348a-4f76-aac2-863d64584788" />

**Comment by meizhong986** [comment]
---  
I just pushed a hotfix to solve both issues: 

1. - Merge of second pass fails in some cases;
2. - App crashes with exit code; 

The issues are interrelated. The first one causes the second one. 

--- 
### Please upgrade to the latest hotfix:
  ───────────────────────────────────────────────────────────────────────────────
                                UPGRADE STEPS
  ───────────────────────────────────────────────────────────────────────────────

  1. Open Windows PowerShell or Command Prompt

  2. Navigate to your WhisperJAV installation folder (v1.7.x):

     cd DRIVE:\PathToWhisperjavInstallationFolder

     (Replace with your actual installation path)

  3. Run the upgrade command:

    .\Scripts\pip.exe install --no-deps --force-reinstall -U git+https://github.com/meizhong986/whisperjav.git

  4. Wait for the installation to complete. You should see:

     Successfully installed whisperjav-1.7.1.post2 or hotfix2

  5. Launch WhisperJAV-GUI as normal. The version display should show "1.7.1 hotfix2"


---


  ───────────────────────────────────────────────────────────────────────────────
                                TROUBLESHOOTING
  ───────────────────────────────────────────────────────────────────────────────

If you encounter any more issues during usage, please select (checkbox) for the debug-output and keep-temp-files in the advanced tab. That will help to report more details and log files. 


Good luck. Let me go how it goes.

**Comment by meizhong986** [comment]
@weifu8435 , can you verify if the issue is fixed? I plan to close this.

**Comment by weifu8435** [comment]
<img width="196" height="157" alt="Image" src="https://github.com/user-attachments/assets/392dda0a-5e6a-4822-8a9f-0447a83435e3" />
After updating to host3, when performing multitasking, only pass1 appears; pass2 and the merged result are not shown. It's a multitasking process where many videos are added at once. Adding one video at a time seems to be working fine so far.

**Comment by meizhong986** [comment]
Do you see debug files in the folder called: ensemble_summary_2025xxxx_xxxxxx.json `example: ensemble_summary_20251211_114115.json`. Can you send those to me. 

Note: the json files have the commands and the path to the files. If you prefer not to share the paths for privacy/security reasons, please feel free to mask/remove them and send me the cleaned ones.

**Comment by weifu8435** [comment]
> Do you see debug files in the folder called: ensemble_summary_2025xxxx_xxxxxx.json `example: ensemble_summary_20251211_114115.json`. Can you send those to me.
> 
> Note: the json files have the commands and the path to the files. If you prefer not to share the paths for privacy/security reasons, please feel free to mask/remove them and send me the cleaned ones.

<img width="481" height="233" alt="Image" src="https://github.com/user-attachments/assets/001f84d3-0e8b-4e46-bc08-fbca2feaa57d" />
This one is also available.

**Comment by weifu8435** [comment]
But it seems to be a different problem. You could try adding multiple videos at once; it seems only pass1 is affected.

**Comment by weifu8435** [comment]
<img width="663" height="215" alt="Image" src="https://github.com/user-attachments/assets/10583e52-bf89-4ffc-8b16-61e2475c1f28" />
<img width="251" height="99" alt="Image" src="https://github.com/user-attachments/assets/7311f597-52b6-4eb4-86de-ac4aad3a1b58" />I tried multitasking again today, and it still didn't work. And it's not the same problem as with the .json file; the dates are different.

**Comment by weifu8435** [comment]
Two issues: 1. When adding multiple videos at once in a multi-task scenario, only "pass1" is displayed.
2. Sometimes, a single-task scenario displays JSON.

**Comment by meizhong986** [comment]
I need to see the json files. Can you upload them here? Or share their content so I can see the debug information.

**Comment by weifu8435** [comment]
I'm more concerned about multitasking; the fact that only one pass1 is showing up makes it unusable.

**Comment by weifu8435** [comment]
Additionally, I noticed that many videos have fewer subtitles in Pass2 than in Pass1, even though Pass2 has higher sensitivity than Pass1.

<img width="1144" height="251" alt="Image" src="https://github.com/user-attachments/assets/e323aa23-6622-4ced-8c9f-aa9062d10746" />

**Comment by meizhong986** [comment]
Thanks for helping to track this down. I have tested it in my side extensively and I don't get any crash or any issues. I suspect that there might be a special condition or glitch in your environment --may be the a memory error, or even a file mgmt. error (handling some Chinese filenames with special non-visible characters). I have seen such errors in the past in other python apps. Sometimes when the media is directly downloaded from streaming sites, the sites have encoded filenames with some non-visible characters that python cannot always handle. If that happens, whisperjav jumps over them.   

So I have added more rail guards to find and catch the root cause.

I have just release version 1.7.2.  Please upgrade to v1.7.2 - it includes better error reporting for this issue.

---

To help diagnose, when processing your next batch:

 1. Go to Advanced Settings tab
 2. Enable both:
   - ☑ Debug Logging
   - ☑ Keep temp files
 3. Go back to Ensemble Tab
 4. Select your options and files
 5. Run your files as usual 


<img width="2058" height="465" alt="Image" src="https://github.com/user-attachments/assets/70117261-ec28-4cf1-8d48-6b69b05fc3be" />

---

This will help that If any issue recurs, we can get more diagnostic information from the console outputand the temp folder. 

If Pass 2 fails again, the console should now show us exactly where things went wrong. You can:
  - Select all the text in the console area (click and drag or click and press Ctrl+A)
  - Copy it (Ctrl+C)
  - Paste it into a message or text file to share with me


Once we see what's actually happening during Pass 2, we should be able to fix it properly. 




---

### About your question regarding number of subtitles in Fidelity | Balanced vs Balanced | Agressive: 

Fidelity pipeline will more likely produce more accurate results than Balanced pipeline. 
Fidelity uses standard whisper models that are two times larger than Balanced, and are usually better in managing noisy environment and accurate transcription;  
Balanced pipeline uses faster whisper that is half the size of Fidelity models. It is two times faster, and it uses half the memory. However it usually creates less accurate than full size Fidelity.  

Please refer to the readme. There is more about the features there.

**Comment by weifu8435** [comment]
Why are there only pass1 and pass2 results in the single video transcription, and no merged results?

[111.txt](https://github.com/user-attachments/files/24142669/111.txt)

**Comment by meizhong986** [comment]
I think you caught it this time. Your pass 2 has crashed after it transcribed everything. 

```
Pass1     | Pass2                                            | Merge | Final                                                                                      
----------+--------------------------------------------------+-------+--------------------------------------------------------------------------------------------
completed | failed: Worker crash: A process in the proces... | NOK   | fallback to pass1 (AVAV001.ja.pass1.srt)
2025-12-13 23:18:46 - whisperjav - INFO - Batch summary saved to C:\Users\a\AppData\Local\Temp\whisperjav\ensemble_summary_20251213_231846.json
2025-12-13 23:18:46 - whisperjav - INFO - Completed: None

```


Can you send me all SRT files for AVAV001.mp4 video: pass1.srt, and pass2.srt and the raw SRT in the subfolder raw_subs.

**Comment by meizhong986** [comment]
Also, in addition to above, can you enable "Keep temp files" and "Debug Logging" on next runs.

**Comment by weifu8435** [comment]
> Also, in addition to above, can you enable "Keep temp files" and "Debug Logging" on next runs.

Sometimes it works, sometimes it doesn't; it doesn't always fail. I've tried this file several times, but it still doesn't work.

[AVAV001.ja.pass1.txt](https://github.com/user-attachments/files/24147269/AVAV001.ja.pass1.txt)
[AVAV001.ja.pass2.txt](https://github.com/user-attachments/files/24147267/AVAV001.ja.pass2.txt)
[AVAV001_stitched.artifacts.txt](https://github.com/user-attachments/files/24147268/AVAV001_stitched.artifacts.txt)
[AVAV001_stitched.original.txt](https://github.com/user-attachments/files/24147266/AVAV001_stitched.original.txt)

**Comment by meizhong986** [comment]
I will inspect those. 

At the moment I suspect the internet-provider for this: the log files that you shared last time when it failed, it showed that whipserjav was not able to download its hallucination filters from github. I suspect that the connection was blocked. I am now investigating if that missing filters might have caused an error. Because the log was showing that the transcription finished and pass 2 completed the subs, and it failed when it was doing the postprocessing sanitization of the subs --which would have needed the filters.

**Comment by meizhong986** [comment]
@weifu8435 ,
This should now be fixed in 1.7.3 release --just released. 
I did extensive testing on my side and passes the test suit.
Please try and let me know. 

Fixing this was quite tricky. The root cause seems to be an issue inside ctranslate2 (faster-whisper) when using chunks that are not 30 seconds long.

**Comment by meizhong986** [comment]
I haven't heard back. I assume the fix is verified. I close this for now.
